# Generated by Django 5.1.4 on 2025-01-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('ssc_roll', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=25, null=True)),
                ('board', models.CharField(blank=True, max_length=25, null=True)),
                ('group', models.CharField(blank=True, max_length=25, null=True)),
                ('quota', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(default='Not Admitted', max_length=100)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
