# Generated by Django 5.2.4 on 2025-08-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='admission_group',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
