# Generated by Django 5.2.4 on 2025-09-03 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_studentadmission_admission_group'),
        ('student', '0003_choice_group_choice_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='admission_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.department'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='student_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentcategory'),
        ),
    ]
