# Generated by Django 5.2.4 on 2025-09-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('student', '0004_subjectchoice_class_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpurpose',
            name='sessions',
            field=models.ManyToManyField(blank=True, null=True, to='student.session'),
        ),
    ]
