# Generated by Django 5.1.4 on 2025-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpurpose',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpurpose',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
