# Generated by Django 5.1.4 on 2025-01-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentpurpose_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpurpose',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
