# Generated by Django 5.1.4 on 2025-01-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentpurpose_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpurpose',
            name='cause',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentpurpose',
            name='cause_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
