# Generated by Django 5.1.4 on 2025-01-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentpurpose_cause_paymentpurpose_cause_en'),
        ('student', '0002_alter_subject_department_alter_subject_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.department'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session'),
        ),
    ]
