# Generated by Django 5.1.4 on 2025-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymenttype_paymentpurpose_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['serial'], 'verbose_name': 'Payment Type', 'verbose_name_plural': 'Payment Type'},
        ),
        migrations.AddField(
            model_name='paymentpurpose',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentpurpose',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
