# Generated by Django 5.1.4 on 2025-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paymenttype_options_paymentpurpose_subtitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentpurpose',
            old_name='amount',
            new_name='amount_bussines',
        ),
        migrations.AddField(
            model_name='paymentpurpose',
            name='amount_humanities',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='paymentpurpose',
            name='amount_science',
            field=models.IntegerField(default=10),
        ),
    ]
