# Generated by Django 5.1.4 on 2025-05-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_amount_paymentpurpose_amount_bussines_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentpurpose',
            old_name='amount_bussines',
            new_name='amount_bussiness',
        ),
    ]
