# Generated by Django 5.1.4 on 2025-06-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymentconsession'),
        ('student', '0008_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconsession',
            name='student_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentcategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentcategory'),
        ),
    ]
