# Generated by Django 5.1.4 on 2025-06-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_paymentconsession_student_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpurpose',
            name='amount_bussiness',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='paymentpurpose',
            name='amount_humanities',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='paymentpurpose',
            name='amount_science',
            field=models.IntegerField(default=10),
        ),
    ]
