# Generated by Django 5.1.4 on 2025-06-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_amount_bussines_paymentpurpose_amount_bussiness'),
        ('payment', '0011_paymentpurpose_amount_bussiness_and_more'),
    ]

    operations = [
    ]
