# Generated by Django 5.2.4 on 2025-09-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_paymentpurpose_sessions'),
        ('student', '0004_subjectchoice_class_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=10)),
                ('template', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_auto_sign', models.BooleanField(default=False)),
                ('is_join_sign', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': ' সনদের ধরণ',
                'verbose_name_plural': ' সনদের ধরণ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('name_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('father_name_eng', models.CharField(max_length=100)),
                ('father_name_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name_eng', models.CharField(max_length=100)),
                ('mother_name_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=25, null=True)),
                ('class_roll', models.CharField(blank=True, max_length=11, null=True)),
                ('exam_roll', models.CharField(blank=True, max_length=25, null=True)),
                ('registration', models.CharField(blank=True, max_length=25, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=4, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=25, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.adress')),
                ('class_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.class')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.department')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('student_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentcategory')),
                ('subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.subjectchoice')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction')),
                ('certificate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.certificatetype')),
            ],
        ),
    ]
