# Generated by Django 5.2.4 on 2025-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='language',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
