# Generated by Django 5.1.4 on 2025-01-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ManyToManyField(blank=True, to='student.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ManyToManyField(blank=True, to='student.group'),
        ),
        migrations.AlterField(
            model_name='subjectchoice',
            name='compulsory_subject',
            field=models.ManyToManyField(blank=True, related_name='compulsory_subject', to='student.subject'),
        ),
        migrations.AlterField(
            model_name='subjectchoice',
            name='optional_subject',
            field=models.ManyToManyField(blank=True, related_name='optional_subject', to='student.subject'),
        ),
    ]
