# Generated by Django 5.2.4 on 2025-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchoice',
            name='compulsory_subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='compulsory_subject', to='student.subject'),
        ),
        migrations.AlterField(
            model_name='subjectchoice',
            name='optional_subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='optional_subject', to='student.subject'),
        ),
    ]
