# Generated by Django 5.2.4 on 2025-09-02 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_subjectchoice_compulsory_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
        migrations.AddField(
            model_name='choice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session'),
        ),
    ]
