# Generated by Django 5.2.4 on 2025-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_choice_group_choice_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchoice',
            name='class_roll',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
