# Generated by Django 5.1.4 on 2025-02-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_district_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('department', models.ManyToManyField(blank=True, to='student.department')),
                ('group', models.ManyToManyField(blank=True, to='student.group')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
