# Generated by Django 5.1.4 on 2025-05-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_testsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/student/%Y'),
        ),
        migrations.AlterField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/student/%Y'),
        ),
    ]
