# Generated by Django 5.1.4 on 2025-07-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_time_alter_attendance_date'),
        ('student', '0008_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.department'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='student_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentcategory'),
        ),
    ]
