# Generated by Django 5.1.4 on 2025-07-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_dailyattendance_department_dailyattendance_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='all',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='business_studies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='humanities',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='science',
            field=models.IntegerField(default=0),
        ),
    ]
